#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service() {
    [ -e /etc/dulwifi-firstboot.done ] && return 0
    procd_open_instance
    procd_set_param command /usr/libexec/dulwifi-firstboot
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
