include $(TOPDIR)/rules.mk

LUCI_TITLE:=TikTok multi WiFi ACL manager
LUCI_DEPENDS:=+luci-base +uci +firewall4
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt build system
